config/routes.rb
Financeiro::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions' }
  resources :authentications

  match '/movimentos/:id/listar' => 'movimentos#listar'
  
  resources :agendas do
    collection do
      get 'template'
      put 'confirmar'
    end
  end
  
  resources :despesas
  resources :cartaos, :has_many => :faturas
  resources :faturas
  
  resources :pagamentos do
    collection do
      put 'confirmar'
    end
  end
  
  resources :contas, :has_many => :movimentos
  resources :tipos
  resources :movimentos
  
  root :to => 'contas#dashboard'
  match ':controller(/:action(/:id(.:format)))'
end

app/models/conta.rb
class Conta < ActiveRecord::Base
  validates_presence_of :nome, :user_id
  
  belongs_to :user
  has_many :movimentos, :order => "dia DESC"
  
  def saldo
    saldo_atual = 0
    
    movimentos.each do |movimento|
      if movimento.tipo.valor == 'C'
        saldo_atual += movimento.valor
      else
        saldo_atual -= movimento.valor
      end
    end
    
    return saldo_atual
  end
  
  def saldo_formatado
    Dinheiro.new(saldo).real_formatado
  end
  
end

app/controllers/contas_controller.rb
class ContasController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /contas
  # GET /contas.xml
  def index
    @contas = Conta.all(:conditions => { :user_id => current_user.id })

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contas }
    end
  end

  # GET /contas/1
  # GET /contas/1.xml
  def show
    @conta = Conta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @conta }
    end
  end

  # GET /contas/new
  # GET /contas/new.xml
  def new
    @conta = Conta.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @conta }
    end
  end

  # GET /contas/1/edit
  def edit
    @conta = Conta.find(params[:id])
  end

  # POST /contas
  # POST /contas.xml
  def create
    @conta = Conta.new(params[:conta])
    @conta.user = current_user

    respond_to do |format|
      if @conta.save
        flash[:notice] = 'Conta cadastrada com sucesso.'
        format.html { redirect_to(@conta) }
        format.xml  { render :xml => @conta, :status => :created, :location => @conta }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @conta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contas/1
  # PUT /contas/1.xml
  def update
    @conta = Conta.find(params[:id])

    respond_to do |format|
      if @conta.update_attributes(params[:conta])
        flash[:notice] = 'Conta atualizada com sucesso.'
        format.html { redirect_to(@conta) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @conta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contas/1
  # DELETE /contas/1.xml
  def destroy
    @conta = Conta.find(params[:id])
    
    if @conta.movimentos.empty?
      @conta.destroy
      flash[:notice] = 'Conta removida com sucesso.'
    else
      flash[:notice] = 'Conta não pode ser removida por possuir movimentações associadas.'
    end

    respond_to do |format|
      format.html { redirect_to(contas_url) }
      format.xml  { head :ok }
    end
  end
  
  def dashboard
    @contas = Conta.all(:conditions => { :user_id => current_user.id })
  end
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/views/contas/dashboard.html.erb
<%= link_to "Dashboard", root_url %> &gt; Resumo

<p>Abaixo o resumo das movimentações das suas contas</p>

<% if @contas.empty? %>
	<p>Você ainda não possui movimentações.</p>
<% end %>

<% for conta in @contas %>
	<p>
		<%= link_to  conta.nome, conta %>
	</p>
	<% meses = conta.movimentos.group_by { |m| m.dia.beginning_of_month } %>
	<table id="newspaper-b">
	  <thead>
		  <tr>
		    <th>Mês</th>
		    <th>Crédito</th>
		    <th>Débito</th>
		    <th>Saldo</th>
		  </tr>
	  </thead>

	  <tbody>
	<%
	credito_total = 0
	despesa_total = 0
	saldo_atual = 0
	%>
	<% meses.sort.each do |mes, movimentos| %>
	<%
	credito_mes = 0
	despesa_mes = 0
	for movimento in movimentos
		if movimento.tipo.valor == 'C'
			credito_mes += movimento.valor
			credito_total += movimento.valor
		else
			despesa_mes += movimento.valor
			despesa_total += movimento.valor
		end
	end

	saldo_atual = (credito_mes - despesa_mes) + saldo_atual
	%>
		<tr>
	      <td><%=h mes.strftime('%m/%Y') %></td>
	      <td nowrap><%=h Dinheiro.new(credito_mes).real_formatado %></td>
	      <td nowrap><%=h Dinheiro.new(despesa_mes).real_formatado %></td>
	      <td nowrap><%=h Dinheiro.new(saldo_atual).real_formatado %></td>
	    </tr>
	<% end %>
		<tr>
		  <td><b>Total</b></td>
		  <td nowrap><b><%=h Dinheiro.new(credito_total).real_formatado %></b></td>
		  <td nowrap><b><%=h Dinheiro.new(despesa_total).real_formatado %></b></td>
		  <td nowrap><b><%=h Dinheiro.new(credito_total - despesa_total).real_formatado %></b></td>
		</tr>
	  </tbody>
	</table>
<% end %>

app/views/contas/edit.html.erb
<%= link_to "Dashboard", root_url %> &gt; <%= link_to "Contas", contas_url %> &gt; Editar conta

<% form_for(@conta) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nome, "Nome:" %>
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.label :descricao, "Descrição" %>
    <%= f.text_area :descricao %>
  </p>
  <p>
    <%= f.submit 'Editar' %> ou <%= link_to 'Voltar', contas_path %>
  </p>
<% end %>

app/views/contas/index.html.erb
<%= link_to "Dashboard", root_url %> &gt; Contas

<table id="newspaper-b">
  <thead>
	  <tr>
	    <th>Nome</th>
	    <th>Descrição</th>
	    <th>Saldo</th>
	    <th>Ações</th>
	  </tr>
  </thead>

  <tbody>
<% @contas.each do |conta| %>
  <tr>
    <td><%=h conta.nome %></td>
    <td><%=h conta.descricao %></td>
    <td><%=h conta.saldo_formatado %></td>
    <td nowrap>
    	<%= link_to 'Extrato', conta %> | 
		<%= link_to 'Editar', edit_conta_path(conta) %> | 
		<%= link_to 'Remover', conta, :confirm => 'Confirma remover a conta?', :method => :delete %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>

<br />

<%= link_to 'Nova conta', new_conta_path %>

app/views/contas/new.html.erb
<%= link_to "Dashboard", root_url %> &gt; <%= link_to "Contas", contas_url %> &gt; Inserir conta

<% form_for(@conta) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :nome, "Nome:" %>
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.label :descricao, "Descrição" %>
    <%= f.text_area :descricao %>
  </p>
  <p>
    <%= f.submit 'Inserir' %> ou <%= link_to 'Voltar', contas_path %>
  </p>
<% end %>

app/views/contas/show.html.erb
<%= link_to "Dashboard", root_url %> &gt; <%= link_to "Contas", contas_url %> &gt; Extrato

<p>
  <b>Nome:</b>
  <%=h @conta.nome %>
</p>

<p>
  <b>Descrição:</b>
  <%=h @conta.descricao %>
</p>

<p>
  <b>Saldo atual:</b>
  <%=h @conta.saldo_formatado %>
</p>

<table id="newspaper-b">
  <thead>
	  <tr>
	    <th>Tipo</th>
	    <th>Dia</th>
	    <th>Descrição</th>
	    <th>Valor</th>
	    <th>Ações</th>
	  </tr>
  </thead>

  <tbody>
<% @conta.movimentos.each do |movimento| %>
  <tr>
    <td><%=h movimento.tipo.nome %></td>
    <td><%=h movimento.dia_to_s %></td>
    <td><%=h movimento.descricao %></td>
    <td nowrap><%=h movimento.valor_formatado %></td>
    <td nowrap>
    	<%= link_to 'Editar', edit_movimento_path(movimento) %> | 
		<%= link_to 'Remover', movimento, :confirm => 'Confirmar remover o movimento?', :controller => 'movimentos', :method => :delete %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>

<p><%= link_to 'Adicionar movimento', new_movimento_path({ :conta_id => @conta.id }) %></p>