config/routes.rb
Financeiro::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions' }
  resources :authentications

  match '/movimentos/:id/listar' => 'movimentos#listar'
  
  resources :agendas do
    collection do
      get 'template'
      put 'confirmar'
    end
  end
  
  resources :despesas
  resources :cartaos, :has_many => :faturas
  resources :faturas
  
  resources :pagamentos do
    collection do
      put 'confirmar'
    end
  end
  
  resources :contas, :has_many => :movimentos
  resources :tipos
  resources :movimentos
  
  root :to => 'contas#dashboard'
  match ':controller(/:action(/:id(.:format)))'
end

app/models/cartao.rb
class Cartao < ActiveRecord::Base
  validates_presence_of :user_id, :descricao, :vencimento
  
  belongs_to :user
  has_many :faturas
  
  def fatura_atual(cartao_id)
    Fatura.find_by_cartao_id_and_situacao(cartao_id, "Aberta")
  end
end

app/controllers/cartaos_controller.rb
class CartaosController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /cartaos
  # GET /cartaos.xml
  def index
    @cartaos = Cartao.all(:conditions => { :user_id => current_user.id })

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cartaos }
    end
  end

  # GET /cartaos/1
  # GET /cartaos/1.xml
  def show
    @cartao = Cartao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cartao }
    end
  end

  # GET /cartaos/new
  # GET /cartaos/new.xml
  def new
    @cartao = Cartao.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cartao }
    end
  end

  # GET /cartaos/1/edit
  def edit
    @cartao = Cartao.find(params[:id])
  end

  # POST /cartaos
  # POST /cartaos.xml
  def create
    @cartao = Cartao.new(params[:cartao])
    @cartao.user = current_user

    respond_to do |format|
      if @cartao.save
        flash[:notice] = 'Cartão cadastrado com sucesso.'
        
        # Criar uma nova fatura
        fatura = Fatura.new
        fatura.cartao = @cartao
        fatura.mes = Date.new(Date.today.year, Date.today.month)
        fatura.situacao = "Aberta"
        fatura.save
        
        format.html { redirect_to(@cartao) }
        format.xml  { render :xml => @cartao, :status => :created, :location => @cartao }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cartao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cartaos/1
  # PUT /cartaos/1.xml
  def update
    @cartao = Cartao.find(params[:id])

    respond_to do |format|
      if @cartao.update_attributes(params[:cartao])
        flash[:notice] = 'Cartão atualizado com sucesso.'
        format.html { redirect_to(@cartao) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cartao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cartaos/1
  # DELETE /cartaos/1.xml
  def destroy
    @cartao = Cartao.find(params[:id])
    if @cartao.faturas.empty?
      @cartao.destroy
    else
      flash[:notice] = 'Cartão não pode ser removido por possuir faturas associadas.'
    end

    respond_to do |format|
      format.html { redirect_to(cartaos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/cartaos_helper.rb
module CartaosHelper
end

app/views/cartaos/edit.html.erb
<%= link_to "Dashboard", root_url %> &gt; <%= link_to "Cartões de crédito", cartaos_url %> &gt; Editar cartão de crédito

<% form_for(@cartao) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :descricao, "Descrição:" %>
    <%= f.text_field :descricao %>
  </p>
  <p>
    Dia de vencimento: <%= select(:cartao, :vencimento, (1..30).to_a) %>
  </p>
  <p>
    <%= f.submit 'Editar' %> ou <%= link_to 'Voltar', cartaos_path %>
  </p>
<% end %>

app/views/cartaos/index.html.erb
<%= link_to "Dashboard", root_url %> &gt; Cartões de crédito

<table id="newspaper-b">
  <thead>
	  <tr>
	    <th>Descrição</th>
	    <th>Dia de vencimento</th>
	    <th>Mês fatura atual</th>
	    <th>Valor atual</th>
	    <th>Ações</th>
	  </tr>
  </thead>
  <tbody>

<% valor_total = 0 %>
<% @cartaos.each do |cartao| %>
  <tr>
    <td><%=h cartao.descricao %></td>
	<td align="center"><%= cartao.vencimento %></td>
	<td><%=h cartao.fatura_atual(cartao.id).mes_formatado %></td>
	<td nowrap><%=h cartao.fatura_atual(cartao.id).saldo_formatado %></td>
    <td nowrap>
	<%= link_to 'Fatura atual', cartao.fatura_atual(cartao.id) %> | 
	<%= link_to 'Faturas', cartao %> | 
	<%= link_to 'Editar', edit_cartao_path(cartao) %> | 
	<%= link_to 'Remover', cartao, :confirm => 'Confirma remover o cartão de crédito?', :method => :delete %>
	</td>
  </tr>
<% valor_total += cartao.fatura_atual(cartao.id).saldo %>
<% end %>
  </tbody>
</table>

<p><b>Valor total atual:</b> <%=h Dinheiro.new(valor_total).real_formatado %></p>

<p><%= link_to 'Novo cartão de crédito', new_cartao_path %></p>

app/views/cartaos/new.html.erb
<%= link_to "Dashboard", root_url %> &gt; <%= link_to "Cartões de crédito", cartaos_url %> &gt; Inserir cartão de crédito

<% form_for(@cartao) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :descricao, "Descrição:" %>
    <%= f.text_field :descricao %>
  </p>
  <p>
    Dia de vencimento: <%= select(:cartao, :vencimento, (1..30).to_a) %>
  </p>
  <p>
    <%= f.submit 'Inserir' %> ou <%= link_to 'Voltar', cartaos_path %>
  </p>
<% end %>

app/views/cartaos/show.html.erb
<%= link_to "Dashboard", root_url %> &gt; <%= link_to "Cartões de crédito", cartaos_url %> &gt; Faturas

<p>
  <b>Cartão de crédito:</b>
  <%=h @cartao.descricao %>
</p>

<p>
  <b>Dia de vencimento:</b>
  <%=h @cartao.vencimento %>
</p>

<table id="newspaper-b">
  <thead>
	  <tr>
	    <th>Mês</th>
	    <th>Vencimento</th>
	    <th>Valor</th>
	    <th>Situação</th>
	    <th>Ações</th>
	  </tr>
  </thead>

  <tbody>
<% @cartao.faturas.each do |fatura| %>
  <tr>
    <td><%=h fatura.mes_formatado %></td>
    <td><%=h fatura.vencimento.to_s_br %></td>
    <td><%=h fatura.saldo_formatado %></td>
    <td nowrap><%=h fatura.situacao %></td>
    <td nowrap>
	<%= link_to 'Detalhe', fatura %>
	</td>
  </tr>
<% end %>
  </tbody>
</table>