config/routes.rb
Financeiro::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions' }
  resources :authentications

  match '/movimentos/:id/listar' => 'movimentos#listar'
  
  resources :agendas do
    collection do
      get 'template'
      put 'confirmar'
    end
  end
  
  resources :despesas
  resources :cartaos, :has_many => :faturas
  resources :faturas
  
  resources :pagamentos do
    collection do
      put 'confirmar'
    end
  end
  
  resources :contas, :has_many => :movimentos
  resources :tipos
  resources :movimentos
  
  root :to => 'contas#dashboard'
  match ':controller(/:action(/:id(.:format)))'
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
  
  validates_presence_of :nome, :vencimento, :valor
  
  belongs_to :user
  belongs_to :agenda
  
  def confirmado_pt
    if confirmado
      return "Sim"
    else
      return "Não"
    end
  end
  
  def vencimento_to_s
    read_attribute(:vencimento).to_s_br
  end
  
  def vencimento_to_s=(vencimento_atual)
    write_attribute(:vencimento, Date.strptime(vencimento_atual, "%d/%m/%Y"))
  end
  
  def valor_formatado
    Dinheiro.new(read_attribute(:valor)).real_formatado
  end
end

app/controllers/pagamentos_controller.rb
class PagamentosController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    if params[:ordenar] == 'confirmado'
      @pagamentos = Pagamento.all(:order => "confirmado DESC", :conditions => { :user_id => current_user.id })
    else
      @pagamentos = Pagamento.all(:order => "vencimento DESC", :conditions => { :user_id => current_user.id })
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pagamentos }
    end
  end

  def new
    if params[:agenda_id] == nil
      flash[:notice] = 'Agenda não encontrada.'
      redirect_to :back
    end
    
    @pagamento = Pagamento.new
    @pagamento.agenda = Agenda.find(params[:agenda_id])
    @pagamento.vencimento = Date.today

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pagamento }
    end
  end

  def edit
    @pagamento = Pagamento.find(params[:id])
  end

  def create
    @pagamento = Pagamento.new(params[:pagamento])
    @pagamento.user = current_user

    respond_to do |format|
      if @pagamento.save
        flash[:notice] = 'Pagamento cadastrado com sucesso.'
        format.html { redirect_to(@pagamento.agenda) }
        format.xml  { render :xml => @pagamento, :status => :created, :location => @pagamento }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pagamento.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @pagamento = Pagamento.find(params[:id])

    respond_to do |format|
      if @pagamento.update_attributes(params[:pagamento])
        flash[:notice] = 'Pagamento atualizado com sucesso.'
        format.html { redirect_to(@pagamento.agenda) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pagamento.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @pagamento = Pagamento.find(params[:id])
    
    agenda_atual = Agenda.find(@pagamento.agenda.id)
    
    @pagamento.destroy

    respond_to do |format|
      flash[:notice] = 'Pagamento removido com sucesso.'
      format.html { redirect_to(agenda_atual) }
      format.xml  { head :ok }
    end
  end
  
  def confirmar
    @pagamento = Pagamento.find(params[:id])
    @pagamento.confirmado = true
    @pagamento.save
    
    respond_to do |format|
      format.js { render "confirmar" }
    end
  end
  
  def cancelar
    @pagamento = Pagamento.find(params[:id])
    @pagamento.confirmado = false
    @pagamento.save
    
    respond_to do |format|
      format.js { render "confirmar" }
    end
  end
end

app/helpers/pagamentos_helper.rb
module PagamentosHelper
end

app/views/pagamentos/_pagamento.html.erb
<tr>
  <td align="center"><%= check_box_tag 'pagamento[]', pagamento.id, true %></td>
  <td><%=h pagamento.nome %></td>
  <td><%=h pagamento.descricao %></td>
  <td><%=h pagamento.vencimento_to_s %></td>
  <td nowrap><%=h pagamento.valor_formatado %></td>
</tr>

app/views/pagamentos/confirmar.js.erb
$("#pagamento_<%= escape_javascript( @pagamento.id.to_s ) %>").html(
	"<%= escape_javascript( pagamento_tag(@pagamento) ) %>");
	
$("#valor_confirmado").html("<%= escape_javascript( @pagamento.agenda.valor_confirmado ) %>");
$("#valor_pendente").html("<%= escape_javascript( @pagamento.agenda.valor_pendente ) %>");

$("#pagamento_<%= escape_javascript( @pagamento.id.to_s ) %>").effect("highlight", {}, 3000);
$("#valor_confirmado").effect("highlight", {}, 3000);
$("#valor_pendente").effect("highlight", {}, 3000);

app/views/pagamentos/edit.html.erb
<%= link_to "Dashboard", root_url %> &gt; 
<%= link_to "Agendas", agendas_url %> &gt; 
<%= link_to "Pagamentos", @pagamento.agenda %> &gt; 
Editar pagamento

<% form_for(@pagamento) do |f| %>
  <%= f.error_messages %>

  <%= f.hidden_field :agenda_id, :value => @pagamento.agenda.id %>

  <p>
    <%= f.label :nome, "Nome:" %>
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.label :descricao, "Descrição:" %>
    <%= f.text_area :descricao %>
  </p>
  <p>
    <%= f.label :vencimento_to_s, "Vencimento:" %>
    <%= f.text_field :vencimento_to_s, :size => 10 %>
  </p>
  <p>
    <%= f.label :valor, "Valor:" %>
    <%= f.text_field :valor %>
  </p>
  <p>
    <%= f.label :confirmado, "Confirmado? " %><%= f.check_box :confirmado %>
  </p>
  <p>
    <%= f.submit 'Editar' %> ou <%= link_to 'Voltar', @pagamento.agenda %>
  </p>
<% end %>

app/views/pagamentos/index.html.erb
<%= link_to "Dashboard", root_url %> &gt; Pagamentos

<table id="newspaper-b">
  <thead>
	  <tr>
	    <th>Nome</th>
	    <th>Descrição</th>
	    <th><%= link_to 'Vencimento', pagamentos_path({ :ordenar => 'vencimento' }) %></th>
	    <th>Valor</th>
	    <th><%= link_to 'Confirmado?', pagamentos_path({ :ordenar => 'confirmado' }) %></th>
	    <th>Ações</th>
	  </tr>
  </thead>

  <tbody>
<% @pagamentos.each do |pagamento| %>
  <tr>
    <td><%=h pagamento.nome %></td>
    <td><%=h pagamento.descricao %></td>
    <td><%=h pagamento.vencimento %></td>
    <td><%=h pagamento.valor %></td>
    <td><%=h pagamento.confirmado_pt %></td>
    <td nowrap>
    	<%= link_to 'Editar', edit_pagamento_path(pagamento) %> | 
		<%= link_to 'Remover', pagamento, :confirm => 'Confirma remover o pagamento?', :method => :delete %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>

<%
	valor_confirmado = 0
	valor_pendente = 0
	Pagamento.all(:conditions => { :user_id => current_user.id }).each do |pagamento|
		if pagamento.confirmado
			valor_confirmado += pagamento.valor
		else
			valor_pendente += pagamento.valor
		end
	end
%>

<p><b>Valor Confirmado:</b> <%=h valor_confirmado %></p>
<p><b>Valor Pendente:</b> <%=h valor_pendente %></p>

<%= link_to 'Novo pagamento', new_pagamento_path %>

app/views/pagamentos/new.html.erb
<%= link_to "Dashboard", root_url %> &gt; 
<%= link_to "Agendas", agendas_url %> &gt; 
<%= link_to "Pagamentos", @pagamento.agenda %> &gt; 
Inserir pagamento

<% form_for(@pagamento) do |f| %>
  <%= f.error_messages %>

  <%= f.hidden_field :agenda_id, :value => @pagamento.agenda.id %>

  <p>
    <%= f.label :nome, "Nome:" %>
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.label :descricao, "Descrição:" %>
    <%= f.text_area :descricao %>
  </p>
  <p>
    <%= f.label :vencimento_to_s, "Vencimento:" %>
    <%= f.text_field :vencimento_to_s, :size => 10 %>
  </p>
  <p>
    <%= f.label :valor, "Valor:" %>
    <%= f.text_field :valor %>
  </p>
  <p>
    <%= f.label :confirmado, "Confirmado? " %><%= f.check_box :confirmado %>
  </p>
  <p>
    <%= f.submit 'Inserir' %> ou <%= link_to 'Voltar', @pagamento.agenda %>
  </p>
<% end %>