config/routes.rb
Financeiro::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions' }
  resources :authentications

  match '/movimentos/:id/listar' => 'movimentos#listar'
  
  resources :agendas do
    collection do
      get 'template'
      put 'confirmar'
    end
  end
  
  resources :despesas
  resources :cartaos, :has_many => :faturas
  resources :faturas
  
  resources :pagamentos do
    collection do
      put 'confirmar'
    end
  end
  
  resources :contas, :has_many => :movimentos
  resources :tipos
  resources :movimentos
  
  root :to => 'contas#dashboard'
  match ':controller(/:action(/:id(.:format)))'
end

app/models/agenda.rb
class Agenda < ActiveRecord::Base
  
  validates_presence_of :nome, :mes
  validates_uniqueness_of :nome, :mes
  
  belongs_to :user
  has_many :pagamentos, :order => "vencimento"
  
  def valor_confirmado
    valor = 0
    pagamentos.each do |pagamento|
      valor += pagamento.valor if pagamento.confirmado
    end
    
    faturas.each do |fatura|
      valor += fatura.saldo if fatura.confirmado
    end
    return Dinheiro.new(valor).real_formatado
  end
  
  def valor_pendente
    valor = 0
    pagamentos.each do |pagamento|
      valor += pagamento.valor unless pagamento.confirmado
    end
    
    faturas.each do |fatura|
      valor += fatura.saldo unless fatura.confirmado
    end
    return Dinheiro.new(valor).real_formatado
  end
  
  def confirmado
    confirmado = true
    pagamentos.each do |pagamento|
      return "Não" unless pagamento.confirmado
    end
    return "Sim"
  end
  
  def mes_formatado
    read_attribute(:mes).strftime("%m/%Y")
  end
  
  def mes_formatado=(mes_atual)
    write_attribute(:mes, Date.strptime(mes_atual, "%m/%Y"))
  end
  
  def faturas
    nil unless :mes
    
    Fatura.where("faturas.mes = ? and cartaos.user_id = ?", self.mes, self.user_id).
      joins("inner join cartaos on faturas.cartao_id = cartaos.id").
      order("cartaos.descricao")
  end
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  
  def provider_name
    if provider == 'open_id'
      "OpenID"
    else
      provider.titleize
    end
  end
end

app/models/cartao.rb
class Cartao < ActiveRecord::Base
  validates_presence_of :user_id, :descricao, :vencimento
  
  belongs_to :user
  has_many :faturas
  
  def fatura_atual(cartao_id)
    Fatura.find_by_cartao_id_and_situacao(cartao_id, "Aberta")
  end
end

app/models/conta.rb
class Conta < ActiveRecord::Base
  validates_presence_of :nome, :user_id
  
  belongs_to :user
  has_many :movimentos, :order => "dia DESC"
  
  def saldo
    saldo_atual = 0
    
    movimentos.each do |movimento|
      if movimento.tipo.valor == 'C'
        saldo_atual += movimento.valor
      else
        saldo_atual -= movimento.valor
      end
    end
    
    return saldo_atual
  end
  
  def saldo_formatado
    Dinheiro.new(saldo).real_formatado
  end
  
end

app/models/despesa.rb
class Despesa < ActiveRecord::Base
  
  validates_presence_of :data, :tipo_id, :parcelas, :valor
  
  belongs_to :fatura
  belongs_to :tipo
  
  def data_br
    read_attribute(:data).to_s_br
  end
  
  def data_br=(data_atual)
    write_attribute(:data, Date.strptime(data_atual, "%d/%m/%Y"))
  end
  
  def valor_formatado
    Dinheiro.new(read_attribute(:valor)).real_formatado
  end
end

app/models/fatura.rb
class Fatura < ActiveRecord::Base
  
  SITUACAO = { :fechada => 'Fechada', :aberta => 'Aberta', :prevista => 'Prevista'}
  
  belongs_to :cartao
  has_many :despesas, :order => "data"
  
  def saldo
    total = 0
    despesas.each { |despesa| total += despesa.valor }
    return total
  end
  
  def saldo_formatado
    Dinheiro.new(saldo).real_formatado
  end
  
  def mes_formatado
    read_attribute(:mes).strftime("%m/%Y")
  end
  
  def proxima_fatura
    mes_proxima_fatura = mes >> 1
    proxima_fatura = Fatura.find_by_cartao_id_and_mes(cartao.id, mes_proxima_fatura)
    
    if proxima_fatura == nil
      proxima_fatura = Fatura.new
      proxima_fatura.cartao = cartao
      proxima_fatura.mes = Date.new(mes_proxima_fatura.year, mes_proxima_fatura.month)
      proxima_fatura.situacao = "Prevista"
      proxima_fatura.save
    end
    
    return proxima_fatura
  end
  
  def vencimento
    Date.new(mes.year, mes.month, cartao.vencimento)
  end
  
  def agenda
    Agenda.find_by_mes(self.mes)
  end
end

app/models/movimento.rb
class Movimento < ActiveRecord::Base
  validates_presence_of :conta_id, :tipo_id, :valor
  
  belongs_to :conta
  belongs_to :tipo
  
  def dia_to_s
    read_attribute(:dia).to_s_br
  end
  
  def dia_to_s=(dia_atual)
    write_attribute(:dia, Date.strptime(dia_atual, "%d/%m/%Y"))
  end
  
  def valor_formatado
    Dinheiro.new(read_attribute(:valor)).real_formatado
  end
end

app/models/notifier.rb
class Notifier < ActionMailer::Base
  default_url_options[:host] = "financeiro.tardivo.org"

  def password_reset_instructions(user)
    subject "Instruções para resetar sua senha"
    from "noreply@tardivo.org"
    recipients user.email
    sent_on Time.now
    body :edit_password_reset_url => edit_password_reset_url(user.perishable_token)
  end
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
  
  validates_presence_of :nome, :vencimento, :valor
  
  belongs_to :user
  belongs_to :agenda
  
  def confirmado_pt
    if confirmado
      return "Sim"
    else
      return "Não"
    end
  end
  
  def vencimento_to_s
    read_attribute(:vencimento).to_s_br
  end
  
  def vencimento_to_s=(vencimento_atual)
    write_attribute(:vencimento, Date.strptime(vencimento_atual, "%d/%m/%Y"))
  end
  
  def valor_formatado
    Dinheiro.new(read_attribute(:valor)).real_formatado
  end
end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
  validates_presence_of :nome
  
  belongs_to :user
  has_many :movimentos
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :authentication
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def apply_omniauth(omniauth)
    # omniauth = { 'user_info' => { 'email' => 'matheustardivo@gmail.com' }, 'provider' => 'github', 'uid' => 'testando' }
    self.email = omniauth['user_info']['email'] if email.blank?
    self.authentication = Authentication.new(:provider => omniauth["provider"], :uid => omniauth["uid"])
  end
  
  def password_required?
    (!authentication || !password.blank?) && super
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/cartaos_helper.rb
module CartaosHelper
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/helpers/despesas_helper.rb
module DespesasHelper
end

app/helpers/faturas_helper.rb
module FaturasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Tardivo.org - Financeiro</title>
  <%= stylesheet_link_tag 'bundle_github' %>
  <%= stylesheet_link_tag 'scaffold' %>
  <%= stylesheet_link_tag 'tables' %>
  <%= stylesheet_link_tag 'style', :media => 'all' %>
  <%= stylesheet_link_tag 'print', :media => 'print' %>

  <%= javascript_include_tag 'dbx.js' %>
  <%= javascript_include_tag 'dbx-key.js' %>

  <%= stylesheet_link_tag 'dbx', :media => 'screen, projection' %>

  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>

  <%= stylesheet_link_tag "jquery-ui.css" %>

  <%= javascript_include_tag "jquery-ui.min.js" %>
  <%= javascript_include_tag "jquery.maskedinput.min.js" %>
</head>
<body>
	<div style="display:none;">
		<%= image_tag "agradient-30medium.gif", :alt => 'preload' %>
	</div>
	
	<div id="page" class="fix">
		<div id="wrapper" class="fix">
			<div id="header" class="fix">
				<h1 class="blogtitle">Tardivo.org</h1>
	      		<div class="description">Financeiro</div>
		    </div>
		
			<div class="pagehead repohead vis-public">
				<ul class="tabs">
					<% if user_signed_in? %>
						<li><%= link_to 'Dashboard', root_path %></li>
						<% unless current_user.authentication %>
						<li><%= link_to 'Usuário', edit_user_registration_path %></li>
						<% end %>

						<li><%= link_to 'Contas', contas_path %></li>
						<li><%= link_to 'Cartões', cartaos_path %></li>
						<li><%= link_to 'Agenda', agendas_path %></li>
						<li><%= link_to 'Tipos', tipos_path %></li>

						<li><%= link_to 'Logout', destroy_user_session_path %></li>
					<% else %>
						<li><%= link_to 'Login', new_user_session_path %></li>
					<% end %>
				</ul>
			</div>
			<div id="container" class="fix">
				<div id="left-col">
					<div id="content">
						<div class="entry">
							<p style="color: green"><%= flash[:notice] %></p>
							<%= yield %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>